// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTd7-rsY-Ovu4byOSChu1hjA3FVkfnm0',
    appId: '1:1068008329021:web:9abee12cc2788a66b0ff54',
    messagingSenderId: '1068008329021',
    projectId: 'hb-demo-168ee',
    authDomain: 'hb-demo-168ee.firebaseapp.com',
    storageBucket: 'hb-demo-168ee.appspot.com',
    measurementId: 'G-3EHVV5N9NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6eO_99KM9zd760joggW0zWFuy2cr-6xU',
    appId: '1:1068008329021:android:6be855e502eb7c76b0ff54',
    messagingSenderId: '1068008329021',
    projectId: 'hb-demo-168ee',
    storageBucket: 'hb-demo-168ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATIo0nm8WK_-H7-J8hscmvRHWRZwSsYic',
    appId: '1:1068008329021:ios:7f1ea739bf5c58fbb0ff54',
    messagingSenderId: '1068008329021',
    projectId: 'hb-demo-168ee',
    storageBucket: 'hb-demo-168ee.appspot.com',
    iosBundleId: 'com.demohb.hbDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATIo0nm8WK_-H7-J8hscmvRHWRZwSsYic',
    appId: '1:1068008329021:ios:7f1ea739bf5c58fbb0ff54',
    messagingSenderId: '1068008329021',
    projectId: 'hb-demo-168ee',
    storageBucket: 'hb-demo-168ee.appspot.com',
    iosBundleId: 'com.demohb.hbDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaTd7-rsY-Ovu4byOSChu1hjA3FVkfnm0',
    appId: '1:1068008329021:web:f97b7689cdd11d50b0ff54',
    messagingSenderId: '1068008329021',
    projectId: 'hb-demo-168ee',
    authDomain: 'hb-demo-168ee.firebaseapp.com',
    storageBucket: 'hb-demo-168ee.appspot.com',
    measurementId: 'G-MNV08CWSH7',
  );

}